name: penjualan_mobile_legend
description: A Mobile Legend Account Marketplace App (No Firebase)
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Library/UI & Features
  cupertino_icons: ^1.0.8
  intl: ^0.20.2

  # Audio (Notif / Sound Event)
  audioplayers: ^6.5.1

  # WhatsApp / Instagram / External Link Launcher
  url_launcher: ^6.3.2

  # Slider promo
  carousel_slider: ^5.1.1

  # Icon sosial & UI lengkap
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
